namespace ENet.NET
{
    public enum ENetProtocolFlag
    {
        ENET_PROTOCOL_COMMAND_FLAG_ACKNOWLEDGE = (1 << 7),
        ENET_PROTOCOL_COMMAND_FLAG_UNSEQUENCED = (1 << 6),

        ENET_PROTOCOL_HEADER_FLAG_PEER_EXTRA = (1 << 13),
        ENET_PROTOCOL_HEADER_FLAG_COMPRESSED = (1 << 14),
        ENET_PROTOCOL_HEADER_FLAG_SENT_TIME = (1 << 15),
        ENET_PROTOCOL_HEADER_FLAG_MASK = ENET_PROTOCOL_HEADER_FLAG_PEER_EXTRA | ENET_PROTOCOL_HEADER_FLAG_COMPRESSED | ENET_PROTOCOL_HEADER_FLAG_SENT_TIME,

        ENET_PROTOCOL_HEADER_SESSION_MASK = (3 << 11),
        ENET_PROTOCOL_HEADER_SESSION_SHIFT = 11
    }
}